apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ydl
  namespace: ydl
spec:
  rules:
    - host: lramm-tuxedo
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: service-ydl
                port: 
                  number: 8080