apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ydl-downloads
  namespace: ydl
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem