apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ydl-pvc-logs
  namespace: ydl
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem